### ISSUE TITLE
1.19.3 support?

### ISSUE THREAD

**Issue by EL-S** [michiruf/MCProxyCommand#2]
It would be very helpful if you could build a release for Minecraft version 1.19.3

Cheers!

**Comment by matt-t-jones** [comment]
+1, would love to be able to use this in 1.19.4

**Comment by matt-t-jones** [comment]
I went ahead and re-compiled this mod for Fabric 1.19.4. https://github.com/matt-t-jones/MCProxyCommand/releases

The velocity plugin did not need updating for me.

**Comment by Skywalker8510** [comment]
matt-t-jones you are awesome

**Comment by michiruf** [comment]
I do not currently plan to bump versions according to https://github.com/michiruf/MCProxyCommand/issues/6
