### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by Thebigboss537** [michiruf/MCProxyCommand#3]
I have everything I need installed, but when I try the command: [proxycommand "server server2"] it doesn't work, if I put the command [/server server2] in the chat it connects normally

**Comment by Thebigboss537** [comment]
- fabric 1.19.2

- fabric modloader: 0.14.13

- mods in the two servers:

![image](https://user-images.githubusercontent.com/93712379/219976673-44aecd1a-4dc2-486f-99da-9e23e2b493ef.png)

- velocity version:

![image](https://user-images.githubusercontent.com/93712379/219977324-950b952f-a602-4142-be8a-03efe7500061.png)

- example video:

https://user-images.githubusercontent.com/93712379/219977652-b00d2635-c3b4-4bba-95a2-c0d0bda3ff8d.mp4

**Comment by michiruf** [comment]
Thanks for the detailed report and sorry for responding so late!
Could you also provide the logs on the velocity and minecraft server?

**Comment by Thebigboss537** [comment]
Hello, nothing appears in the logs


https://user-images.githubusercontent.com/93712379/221728384-6ff152c0-4add-4c91-89ee-19c922ae279a.mp4

**Comment by michiruf** [comment]
Ok I can't really understand whats happening there. I need to reproduce this with the exact mods that you have. If you would like you could also upload your instances if that would be ok for you.

**Comment by Thebigboss537** [comment]
I already solved the error, I did not have the plugin installed in velocity, I have a question, what is the permission for users to execute the proxycommand? It is that the command is not executed for players when going through a serverportal

**Comment by michiruf** [comment]
Proxycommand requires a permission of 2 or above, so Command Blocks can execute it, where players cannot.
Related to your issue https://github.com/michiruf/MCServerPortals/issues/2 here, this might be needed to be configurable.

**Comment by ekristen** [comment]
@Thebigboss537 I can't seem to make this work either, when you say you didn't have it installed with velocity what didn't you have installed? Thanks.
