### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by GeraldTM** [michiruf/MCProxyCommand#4]

**Comment by GeraldTM** [comment]
I've created a pr for this, it should work but might need tweaking

**Comment by GeraldTM** [comment]
Will close when it is merged

**Comment by Goldenfreddy0703** [comment]
Hey @GeraldTM , really sorry to bother you but i compiled your pr using the gradlew.bat and tried to find the jar file but im a bit stuck and cannot find the right .jar file in the build folder. 

![image](https://github.com/michiruf/MCProxyCommand/assets/62456796/c1aaeacf-0698-4517-9a4b-19a5544ced79)
If you could provide me the jar file or direct me to the right jar file, that would be awesome if could. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so forget about what i said above, I got someone to help me compile the jar and managed to get the jar file and the mod working. Huge thank you to @michiruf for making this excellent mod and huge thank you to @GeraldTM for porting it to 1.20. Without this mod, i would not be able to make server portals in my fabric server. 

Again huge thank you and btw sorry for the ping. 

For anyone else who tried compiling the fabric mod, here are the jar files for them for 1.20 
[proxy-command-fabric-1.0-7.zip](https://github.com/michiruf/MCProxyCommand/files/12052319/proxy-command-fabric-1.0-7.zip)

**Comment by GeraldTM** [comment]
@Goldenfreddy0703 Sry I could not reply, I was away. I'm glad you found my work useful

**Comment by Goldenfreddy0703** [comment]
Hey @GeraldTM glad to hear from you, again huge thank you for making this port. Without this mod, server portals would not have worked in my multiserver and there would be no other mod like this.

Again, huge thank you.

**Comment by GeraldTM** [comment]
Quick update:

I've decided to upload this to modrinth myself as this project seems to be abandoned. Once it is reviewed, both the mod and velocity plug-in will be uploaded under the slug proxy-command-reloaded
