### ISSUE TITLE
Still Maintained? [1.20 Support]

### ISSUE THREAD

**Issue by axelcypher** [michiruf/MCProxyCommand#6]
Hello there,

is this Mod still maintained, and will eventually updated to 1.20?

**Comment by michiruf** [comment]
Hi there, currently theres no planned maintenance, since I do not know how to have multiple version withing one gradle project supported. Bumping the version is not what I currently planning to do.

**Comment by GeraldTM** [comment]
Hey @axelcypher 

I've ported it to 1.20, it is available on modrinth at https://modrinth.com/plugin/proxy-command-reloaded, and the source is at https://github.com/GeraldTM/MCProxyCommand

**Comment by ofulusan** [comment]
> Hey @axelcypher
> 
> I've ported it to 1.20, it is available on modrinth at https://modrinth.com/plugin/proxy-command-reloaded, and the source is at https://github.com/GeraldTM/MCProxyCommand

Is it not possible to fork MCInvSync to support 1.20.1?

**Comment by GeraldTM** [comment]
Haven't tried

**Comment by ofulusan** [comment]
> Haven't tried

If possible, can you make it compatible with 1.20.1?
I would like to ask if you have time.

**Comment by GeraldTM** [comment]
I am extremely busy at this time, if I get some free time (might not be for a couple months) I'll consider it

**Comment by michiruf** [comment]
This will be the last mod that I will try to port to multiple MC versions (which I did with some others already). Will probably take long since this will have a more complex testing environment.

**Comment by GeraldTM** [comment]
Alr
